server:
  port: 18089

#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.204.201:3306/zues?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    username: root
    password: bakheet001
    url: jdbc:mysql://192.168.4.77:3306/zues?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver