server:
  port: 18089

#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.204.201:3306/zues?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
#    driver-class-name: com.mysql.cj.jdbc.Driver

debug: true
spring:
  #应用名称
  application:
    name: zeus
  #环境配置
  profiles:
    active: dev
  #RabbitMQ配置
  rabbitmq:
    addresses: 192.168.7.81:5672
    listener:
      simple:
        default-requeue-rejected: false
    password: admin
    publisher-confirm-type: simple
    username: admin
    virtual-host: /

  #Redis配置
  redis:
    host: 192.168.7.81
    password: root
    pool:
      maxActive: 500
      maxIdle: 30
      maxWait: -1
      minIdle: 0
    port: 6379
    timeout: 3000
  #Datasource配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.4.77:3306/zues?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

#日志配置
logging:
  charset:
    file: UTF-8
  file:
    name: ../logs/zeus.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7
  #  pattern:
  #    console: '%clr(%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n)'
  #    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} >>> [%thread] >>> %-5level >>> %logger{50} >>> %msg%n'
  level:
    com.hml.ztp.zues: debug

materials:
  IDCard:
    face: src/main/resources/static/images/
    back: src/main/resources/static/images/

sftp:
  client:
    protocol: sftp
    host: 192.168.4.15
    port: 22
    username: root
    password: 123_dow_456
    root: /home/tester/
    sessionConnectTimeout: 15000
    channelConnectedTimeout: 15000
    sessionStrictHostKeyChecking: no
    passphrase: yes

imagePath:
  baseDir: src/main/resources/static/images/
  targetDir: images/